-name: Copy and install Firefox
  hosts: "{{ win_hosts }}"
  gather_facts: False
  
  tasks:
    - name: run a powershell script
      script: powershell/copy-firefox.ps1
      register: out
    - debug: var=out
