---
- win_copy:
    src: \\10.1.149.11\test
    dest: C:\windows\tools
    remote_src: yes
  become: yes
  become_method: runas
  become_flags: logon_type=new_credential logon_flags=netcredentials_only
  vars:
    ansible_become_user: user
    ansible_become_pass: pass
