---
- win_copy:
    src: \\ITSATWTVANS01\Source\Apps\Firefox\79.0-EN-x64\Firefox79.0.msi
    dest: C:\Temp\
    remote_src: yes
  become: yes
  become_method: runas
  become_flags: logon_type=new_credential logon_flags=netcredentials_only
  vars:
    ansible_become_user: user
    ansible_become_pass: pass
