---
- name: Copy
  win_copy:
    src: \\ITSATWTVANS01\Source\Apps\Firefox\79.0-EN-x64\Firefox79.0.msi
    dest: C:\Temp\Firefox79.0.msi
    force: yes
    
    #vars:
    #ansible_become_user: '{{ service_user }}'
    #ansible_become_password: '{{ service_pass }}'

- name: Install an MSI Firefox 79.0 EN ESR x64, and wait for it to complete before continuing
  win_package:
    path: C:\Temp\Firefox79.0.msi
    state: present
    log_path: C:\Firefox_install.log
